src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom ne doit pas etre vide.")
     * @Assert\Length(min=3, max=255, minMessage="Le nom du produit doit faire 3 caractères minimum")
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le prix ne doit pas etre vide.")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="L'image est obligatoire")
     */
    private $main_picture;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="La description du produit est obligatoire")
     * @Assert\Length(min=20, minMessage="La description du produit doit faire au moins 20 caractères")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseItem::class, mappedBy="product")
     */
    private $purchaseItems;

    public function __construct()
    {
        $this->purchaseItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(string $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|PurchaseItem[]
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Cart\CartService;
use App\Form\CartConfirmationType;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    protected $productRepository;
    protected $cartService;

    public function __construct(CartService $cartService, ProductRepository $productRepository)
    {
        $this->productRepository = $productRepository;
        $this->cartService = $cartService;
    }

    #[Route('/cart', name: 'cart_show')]
    public function show()
    {
        $form = $this->createForm(CartConfirmationType::class);

        $detailledCart = $this->cartService->getDetailedCart();
        $total = $this->cartService->getTotal();

        return $this->render("cart/show.html.twig", [
            'items' => $detailledCart,
            'total' => $total,
            'confirmationForm' => $form->createView(),
        ]);
    }

    #[Route('/cart/add/{id}', name: 'cart_add', requirements: ['id' => "\d+"])]
    public function add($id, Request $request, ProductRepository $productRepository)
    {
        // Verification d'existance
        $product = $productRepository->find($id);
        if (!$product) {
            throw $this->createNotFoundException("Le product $id n'existe pas.");
        }

        $this->cartService->add($id);

        $this->addFlash("success", "Le produit à bien été rajouter au panier");

        return new RedirectResponse($request->headers->get('referer'));
    }

    #[Route('/cart/remove/{id}', name: 'cart_remove', requirements: ['id' => "\d+"])]
    public function remove($id, Request $request, ProductRepository $productRepository)
    {
        // Verification d'existance
        $product = $productRepository->find($id);
        if (!$product) {
            throw $this->createNotFoundException("Le product $id n'existe pas.");
        }

        $this->cartService->decrement($id);

        $this->addFlash("success", "Le produit a ete retirer");

        return new RedirectResponse($request->headers->get('referer'));
    }

    #[Route('/cart/delete/{id}', name: 'cart_delete', requirements: ['id' => "\d+"])]
    public function delete($id)
    {
        $product = $this->productRepository->find($id);

        if (!$product) {
            throw $this->createNotFoundException("Ce produit n'existe pas");
        }

        $this->cartService->remove($id);

        $this->addFlash("success", "Le produit a ete supprimer");

        return $this->redirectToRoute("cart_show");
    }
}

templates/cart/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Panier
{% endblock %}

{% block carousel %}{% endblock %}

{% block body %}
	<div class="container" style="padding:5% 0%;">
		<div class="row text-center">
			<h1>Votre panier</h1>
		</div>
		<div class="row">
			{% if items | length > 0 %}
				<div class="col-md-8">
					<table class="table">
						<thead>
							<tr>
								<th></th>
								<th>Produit</th>
								<th>Prix</th>
								<th>Quantité</th>
								<th>Total</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							{% for item in items %}
								<tr>
									<td><img src="{{ item.product.mainPicture }}" alt="100" style="width:50px"></td>
									<td>{{ item.product.name }}</td>
									<td>{{ item.product.price }}</td>
									<td>
										<a href="{{ path('cart_remove', {'id':item.product.id}) }}" class="btn btn-sm btn-danger">
											<i class="fas fa-minus"></i>
										</a>
										{{ item.qty }}
										<a href="{{ path('cart_add', {'id':item.product.id}) }}" class="btn btn-sm btn-success">
											<i class="fas fa-plus"></i>
										</a>
									</td>
									<td>{{ item.total }}</td>
									<td>
										<a href="{{ path('cart_delete', {'id':item.product.id}) }}" class="btn btn-sm btn-danger">
											<i class="fas fa-trash"></i>
										</a>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<div class="col-md-4">
					<div class="row">
						<div class="col-md-5">
							<h3>Total :</h3>
						</div>
						<div class="col-md-3">
							<h3 class="text-right">{{ total | amount }}</h3>
						</div>
					</div>
					<hr>
					<div class="row">
						{% if app.user %}
							<h4 class="text-center">Confirmer votre commande en remplissant votre formulaire</h2>

							{{ form_start(confirmationForm, {'action': path('purchase_confirm')}) }}

							{# {{ form_widget(confirmationForm) }} #}

							<div class="form-outline mb-3">
								{{ form_widget(confirmationForm.fullName) }}
								<label class="form-label" for="formControlLg">Nom & Prénom</label>
							</div>

							<div class="form-outline mb-3">
								{{ form_widget(confirmationForm.address) }}
								<label class="form-label" for="formControlLg">Adresse de livraison</label>
							</div>

							<div class="form-outline mb-3">
								{{ form_widget(confirmationForm.postalCode) }}
								<label class="form-label" for="formControlLg">Code postale</label>
							</div>

							<div class="form-outline mb-3">
								{{ form_widget(confirmationForm.city) }}
								<label class="form-label" for="formControlLg">Ville</label>
							</div>

							<div class="text-center">
								<button class="btn btn-success" type="submit">Paiement</button>
							</div>

							{{ form_end(confirmationForm) }}

						{% else %}
							<h5 class="text-center">Connectez-vous pour confirmer votre commande</h2>
							<a href="{{ path('security_login') }}" class="btn btn-success">Me connecter</a>
							<h6 class="text-center">ou</h6>
							<a href="{{ path('security_login') }}" class="btn btn-dark">Me connecter</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>

	{% else %}
		<h2 class="text-center">Le panier est vide</h2>
	{% endif %}
</div>{% endblock %}